# Generated by Django 4.2.3 on 2023-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclient',
            name='c_email',
            field=models.EmailField(max_length=254),
        ),
    ]
