# Generated by Django 4.2.3 on 2023-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_paid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=9),
            preserve_default=False,
        ),
    ]
