# Generated by Django 4.2.3 on 2023-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_total_paid_order_paid_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivery in Progress', 'Delivery in Progress'), ('Delivered', 'Delivered'), ('Stopped', 'Stopped')], max_length=150),
        ),
    ]
