# Generated by Django 4.2.3 on 2023-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
