# Generated by Django 4.2.3 on 2023-07-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivery in Progress', 'Delivery in Progress'), ('Delivered', 'Delivered'), ('Stopped by custom', 'Stopped by custom')], default='Pending', max_length=150),
        ),
    ]
