# Generated by Django 4.2.3 on 2023-07-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_balance_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Country',
            new_name='country',
        ),
    ]
