# Generated by Django 4.2.3 on 2023-07-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='balance',
            new_name='sub_total',
        ),
    ]
